"""Motion planner runtime framework."""

from .backend import GlobalSetpointBackend, GlobalTrajectoryBackend, OnlineMpcBackend
from .command_sink import (
    CommandSink,
    DirectRobotCommandSink,
    EMCommandSink,
    RecordingCommandSink,
    make_command_sink,
)
from .contracts import (
    CurrentState,
    HorizonPlanPoint,
    HorizonPlanResult,
    JointTarget,
    PoseTarget,
    SetpointPlanResult,
    StartState,
    Target,
    TrajectoryPlanPoint,
    TrajectoryPlanResult,
    World,
    WorldBox,
    WorldCapsule,
    WorldMesh,
    WorldPointCloud,
    WorldPose,
    WorldSphere,
    WorldVoxelGrid,
)
from .planner_manager import PlannerManager, PlannerRegistry, PlannerSpec
from .planner_sources import (
    GlobalSetpointPlannerSource,
    GlobalSetpointSourceConfig,
    GlobalTrajectoryPlannerRuntime,
    OnlineMpcPlannerSource,
    OnlineMpcSourceConfig,
    PlannerSourceConfig,
)
from .robot_context import (
    CachedJointStateProvider,
    ExecutionFeedback,
    ExecutionFeedbackProvider,
    RobotContext,
    RobotModelInfo,
    RobotModelProvider,
    RobotStateProvider,
    StaticRobotModelProvider,
)

__all__ = [
    "CachedJointStateProvider",
    "CommandSink",
    "CurrentState",
    "DirectRobotCommandSink",
    "EMCommandSink",
    "ExecutionFeedback",
    "ExecutionFeedbackProvider",
    "GlobalSetpointBackend",
    "GlobalSetpointPlannerSource",
    "GlobalSetpointSourceConfig",
    "GlobalTrajectoryBackend",
    "GlobalTrajectoryPlannerRuntime",
    "HorizonPlanPoint",
    "HorizonPlanResult",
    "JointTarget",
    "OnlineMpcBackend",
    "OnlineMpcPlannerSource",
    "OnlineMpcSourceConfig",
    "PlannerManager",
    "PlannerRegistry",
    "PlannerSourceConfig",
    "PlannerSpec",
    "PoseTarget",
    "RecordingCommandSink",
    "RobotContext",
    "RobotModelInfo",
    "RobotModelProvider",
    "RobotStateProvider",
    "SetpointPlanResult",
    "StartState",
    "StaticRobotModelProvider",
    "Target",
    "TrajectoryPlanPoint",
    "TrajectoryPlanResult",
    "World",
    "WorldBox",
    "WorldCapsule",
    "WorldMesh",
    "WorldPointCloud",
    "WorldPose",
    "WorldSphere",
    "WorldVoxelGrid",
    "make_command_sink",
]
